"""add_is_walk_in_to_clients

Revision ID: 1679cddf0188
Revises: df4d148d9a3a
Create Date: 2026-03-03 21:28:00.977576
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1679cddf0188'
down_revision: Union[str, None] = 'df4d148d9a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('is_walk_in', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'is_walk_in')
    # ### end Alembic commands ###
