"""add financial fields and tax settings

Revision ID: 16d04143a00c
Revises: 8b8d792561af
Create Date: 2026-03-01 20:45:16.508254
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '16d04143a00c'
down_revision: Union[str, None] = '8b8d792561af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('total_price_cents', sa.Integer(), server_default='0', nullable=False))
    op.add_column('appointments', sa.Column('deposit_amount_cents', sa.Integer(), server_default='0', nullable=False))
    op.add_column('studio_settings', sa.Column('vat_percent', sa.Numeric(precision=5, scale=2), server_default='17.00', nullable=False))
    op.add_column('studio_settings', sa.Column('income_tax_percent', sa.Numeric(precision=5, scale=2), server_default='10.00', nullable=False))
    op.add_column('studio_settings', sa.Column('social_security_percent', sa.Numeric(precision=5, scale=2), server_default='5.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studio_settings', 'social_security_percent')
    op.drop_column('studio_settings', 'income_tax_percent')
    op.drop_column('studio_settings', 'vat_percent')
    op.drop_column('appointments', 'deposit_amount_cents')
    op.drop_column('appointments', 'total_price_cents')
    # ### end Alembic commands ###
