"""add_payments

Revision ID: 28e0ba1340a4
Revises: 93d265abf102
Create Date: 2026-02-24 22:20:30.362586
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '28e0ba1340a4'
down_revision: Union[str, None] = '93d265abf102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('external_ref', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('cash','bit','credit','paypal','bank','other')", name='ck_payments_method'),
    sa.CheckConstraint("status IN ('pending','paid','void')", name='ck_payments_status'),
    sa.CheckConstraint("type IN ('deposit','payment','refund')", name='ck_payments_type'),
    sa.CheckConstraint('amount_cents >= 0', name='ck_payments_amount_nonneg'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_appointment_id'), 'payments', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_payments_client_id'), 'payments', ['client_id'], unique=False)
    op.create_index(op.f('ix_payments_studio_id'), 'payments', ['studio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_studio_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_client_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_appointment_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
