"""Add google_calendar fields

Revision ID: 2a981732826a
Revises: 75bbb7353a98
Create Date: 2026-02-28 17:33:03.353881
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2a981732826a'
down_revision: Union[str, None] = '75bbb7353a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
