"""add_birthday_settings

Revision ID: 474334993f0c
Revises: 8a857bba4354
Create Date: 2026-03-07 15:08:41.671514
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '474334993f0c'
down_revision: Union[str, None] = '8a857bba4354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studio_settings', sa.Column('birthday_wa_template', sa.Text(), nullable=True))
    op.add_column('studio_settings', sa.Column('birthday_email_template', sa.Text(), nullable=True))
    op.add_column('studio_settings', sa.Column('birthday_benefit_percent', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studio_settings', 'birthday_benefit_percent')
    op.drop_column('studio_settings', 'birthday_email_template')
    op.drop_column('studio_settings', 'birthday_wa_template')
    # ### end Alembic commands ###
