"""add payment tracking fields to appointment

Revision ID: 47913cd36090
Revises: affec8ac6c5f
Create Date: 2026-03-01 21:17:25.057940
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '47913cd36090'
down_revision: Union[str, None] = 'affec8ac6c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('payment_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appointments', sa.Column('payment_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'payment_verified_at')
    op.drop_column('appointments', 'payment_sent_at')
    # ### end Alembic commands ###
