"""Add stock_quantity and ProductSale

Revision ID: 4eabebc19696
Revises: 036e754d58a1
Create Date: 2026-03-14 17:20:42.773220
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4eabebc19696'
down_revision: Union[str, None] = '036e754d58a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('total_price_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_sales_payment_id'), 'product_sales', ['payment_id'], unique=False)
    op.create_index(op.f('ix_product_sales_product_id'), 'product_sales', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_sales_studio_id'), 'product_sales', ['studio_id'], unique=False)
    op.add_column('products', sa.Column('stock_quantity', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock_quantity')
    op.drop_index(op.f('ix_product_sales_studio_id'), table_name='product_sales')
    op.drop_index(op.f('ix_product_sales_product_id'), table_name='product_sales')
    op.drop_index(op.f('ix_product_sales_payment_id'), table_name='product_sales')
    op.drop_table('product_sales')
    # ### end Alembic commands ###
