"""fix_missing_calendar_hours

Revision ID: 5aec72b895b6
Revises: 3cd58121996f
Create Date: 2026-03-01 13:26:24.447401
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5aec72b895b6'
down_revision: Union[str, None] = '3cd58121996f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studio_settings', sa.Column('calendar_start_hour', sa.String(length=16), server_default='08:00', nullable=False))
    op.add_column('studio_settings', sa.Column('calendar_end_hour', sa.String(length=16), server_default='23:00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studio_settings', 'calendar_end_hour')
    op.drop_column('studio_settings', 'calendar_start_hour')
    # ### end Alembic commands ###
