"""add_landing_page_customs

Revision ID: 722574431957
Revises: b4843057bc06
Create Date: 2026-03-01 14:59:53.018597
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '722574431957'
down_revision: Union[str, None] = 'b4843057bc06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studio_settings', sa.Column('landing_page_bg_image', sa.String(length=255), nullable=True))
    op.add_column('studio_settings', sa.Column('landing_page_title_font', sa.String(length=128), server_default='Heebo', nullable=True))
    op.add_column('studio_settings', sa.Column('landing_page_desc_font', sa.String(length=128), server_default='Assistant', nullable=True))
    op.add_column('studio_settings', sa.Column('landing_page_image_1', sa.String(length=255), nullable=True))
    op.add_column('studio_settings', sa.Column('landing_page_image_2', sa.String(length=255), nullable=True))
    op.add_column('studio_settings', sa.Column('landing_page_image_3', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studio_settings', 'landing_page_image_3')
    op.drop_column('studio_settings', 'landing_page_image_2')
    op.drop_column('studio_settings', 'landing_page_image_1')
    op.drop_column('studio_settings', 'landing_page_desc_font')
    op.drop_column('studio_settings', 'landing_page_title_font')
    op.drop_column('studio_settings', 'landing_page_bg_image')
    # ### end Alembic commands ###
