"""Add google_calendar fields

Revision ID: 75bbb7353a98
Revises: e5eef44da051
Create Date: 2026-02-28 17:33:00.074403
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '75bbb7353a98'
down_revision: Union[str, None] = 'e5eef44da051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studio_settings', sa.Column('google_calendar_client_id', sa.String(length=255), nullable=True))
    op.add_column('studio_settings', sa.Column('google_calendar_client_secret', sa.String(length=255), nullable=True))
    op.add_column('studio_settings', sa.Column('google_calendar_refresh_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studio_settings', 'google_calendar_refresh_token')
    op.drop_column('studio_settings', 'google_calendar_client_secret')
    op.drop_column('studio_settings', 'google_calendar_client_id')
    # ### end Alembic commands ###
