"""add points_on_signup to studio settings

Revision ID: 82c42a87e991
Revises: 722574431957
Create Date: 2026-03-01 17:19:20.964667
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '82c42a87e991'
down_revision: Union[str, None] = '722574431957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studio_settings', sa.Column('points_on_signup', sa.Integer(), server_default='50', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studio_settings', 'points_on_signup')
    # ### end Alembic commands ###
