"""Add payroll fields and work_sessions table

Revision ID: 83f8238edcd4
Revises: c31fa8a1da41
Create Date: 2026-03-14 14:42:47.108200
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '83f8238edcd4'
down_revision: Union[str, None] = 'c31fa8a1da41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_pay', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_sessions_studio_id'), 'work_sessions', ['studio_id'], unique=False)
    op.create_index(op.f('ix_work_sessions_user_id'), 'work_sessions', ['user_id'], unique=False)
    op.add_column('users', sa.Column('pay_type', sa.String(length=16), server_default='none', nullable=False))
    op.add_column('users', sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    op.add_column('users', sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'commission_rate')
    op.drop_column('users', 'hourly_rate')
    op.drop_column('users', 'pay_type')
    op.drop_index(op.f('ix_work_sessions_user_id'), table_name='work_sessions')
    op.drop_index(op.f('ix_work_sessions_studio_id'), table_name='work_sessions')
    op.drop_table('work_sessions')
    # ### end Alembic commands ###
