"""add_cancel_templates

Revision ID: 8a857bba4354
Revises: 1679cddf0188
Create Date: 2026-03-06 17:49:47.705551
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8a857bba4354'
down_revision: Union[str, None] = '1679cddf0188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studio_settings', sa.Column('cancel_wa_template', sa.Text(), nullable=True))
    op.add_column('studio_settings', sa.Column('cancel_email_template', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studio_settings', 'cancel_email_template')
    op.drop_column('studio_settings', 'cancel_wa_template')
    # ### end Alembic commands ###
