"""add cancellation trackers

Revision ID: 8b8d792561af
Revises: b14bfa4f8423
Create Date: 2026-03-01 20:29:23.860906
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8b8d792561af'
down_revision: Union[str, None] = 'b14bfa4f8423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('cancellation_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('clients', sa.Column('no_show_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'no_show_count')
    op.drop_column('clients', 'cancellation_count')
    # ### end Alembic commands ###
