"""add_appointments_and_user_color

Revision ID: 93d265abf102
Revises: c71943d91b10
Create Date: 2026-02-24 21:29:32.631078
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '93d265abf102'
down_revision: Union[str, None] = 'c71943d91b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('scheduled','done','canceled','no_show')", name='ck_appointments_status'),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_artist_id'), 'appointments', ['artist_id'], unique=False)
    op.create_index(op.f('ix_appointments_client_id'), 'appointments', ['client_id'], unique=False)
    op.create_index(op.f('ix_appointments_ends_at'), 'appointments', ['ends_at'], unique=False)
    op.create_index(op.f('ix_appointments_starts_at'), 'appointments', ['starts_at'], unique=False)
    op.create_index(op.f('ix_appointments_studio_id'), 'appointments', ['studio_id'], unique=False)
    op.drop_constraint(op.f('uq_clients_studio_email'), 'clients', type_='unique')
    op.drop_constraint(op.f('uq_clients_studio_phone'), 'clients', type_='unique')
    op.add_column('users', sa.Column('calendar_color', sa.String(length=16), nullable=True))
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_studio_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_studio_id'), 'users', ['studio_id'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.drop_column('users', 'calendar_color')
    op.create_unique_constraint(op.f('uq_clients_studio_phone'), 'clients', ['studio_id', 'phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_clients_studio_email'), 'clients', ['studio_id', 'email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_appointments_studio_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_starts_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_ends_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_client_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_artist_id'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
