"""add smtp and whatsapp settings

Revision ID: a295e9ff1025
Revises: 4f0b7a2d9c10
Create Date: 2026-02-28 14:55:31.251284
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a295e9ff1025'
down_revision: Union[str, None] = '4f0b7a2d9c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_points_ledger_studio_client'), table_name='client_points_ledger')
    op.create_index(op.f('ix_client_points_ledger_client_id'), 'client_points_ledger', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_points_ledger_studio_id'), 'client_points_ledger', ['studio_id'], unique=False)
    op.drop_index(op.f('ix_message_jobs_due'), table_name='message_jobs')
    op.drop_index(op.f('ix_message_jobs_studio'), table_name='message_jobs')
    op.create_index(op.f('ix_message_jobs_client_id'), 'message_jobs', ['client_id'], unique=False)
    op.create_index(op.f('ix_message_jobs_scheduled_at'), 'message_jobs', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_message_jobs_status'), 'message_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_message_jobs_studio_id'), 'message_jobs', ['studio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_jobs_studio_id'), table_name='message_jobs')
    op.drop_index(op.f('ix_message_jobs_status'), table_name='message_jobs')
    op.drop_index(op.f('ix_message_jobs_scheduled_at'), table_name='message_jobs')
    op.drop_index(op.f('ix_message_jobs_client_id'), table_name='message_jobs')
    op.create_index(op.f('ix_message_jobs_studio'), 'message_jobs', ['studio_id'], unique=False)
    op.create_index(op.f('ix_message_jobs_due'), 'message_jobs', ['status', 'scheduled_at'], unique=False)
    op.drop_index(op.f('ix_client_points_ledger_studio_id'), table_name='client_points_ledger')
    op.drop_index(op.f('ix_client_points_ledger_client_id'), table_name='client_points_ledger')
    op.create_index(op.f('ix_points_ledger_studio_client'), 'client_points_ledger', ['studio_id', 'client_id'], unique=False)
    # ### end Alembic commands ###
