"""add message templates and payment links

Revision ID: affec8ac6c5f
Revises: 16d04143a00c
Create Date: 2026-03-01 21:05:55.887142
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'affec8ac6c5f'
down_revision: Union[str, None] = '16d04143a00c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studio_settings', sa.Column('bit_link', sa.Text(), nullable=True))
    op.add_column('studio_settings', sa.Column('paybox_link', sa.Text(), nullable=True))
    op.add_column('studio_settings', sa.Column('welcome_wa_template', sa.Text(), nullable=True))
    op.add_column('studio_settings', sa.Column('welcome_email_template', sa.Text(), nullable=True))
    op.add_column('studio_settings', sa.Column('confirm_wa_template', sa.Text(), nullable=True))
    op.add_column('studio_settings', sa.Column('confirm_email_template', sa.Text(), nullable=True))
    op.add_column('studio_settings', sa.Column('reminder_wa_template', sa.Text(), nullable=True))
    op.add_column('studio_settings', sa.Column('reminder_email_template', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studio_settings', 'reminder_email_template')
    op.drop_column('studio_settings', 'reminder_wa_template')
    op.drop_column('studio_settings', 'confirm_email_template')
    op.drop_column('studio_settings', 'confirm_wa_template')
    op.drop_column('studio_settings', 'welcome_email_template')
    op.drop_column('studio_settings', 'welcome_wa_template')
    op.drop_column('studio_settings', 'paybox_link')
    op.drop_column('studio_settings', 'bit_link')
    # ### end Alembic commands ###
