"""add points_percent_per_payment

Revision ID: b14bfa4f8423
Revises: fff879aa5769
Create Date: 2026-03-01 19:37:31.510002
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b14bfa4f8423'
down_revision: Union[str, None] = 'fff879aa5769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studio_settings', sa.Column('points_percent_per_payment', sa.Integer(), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studio_settings', 'points_percent_per_payment')
    # ### end Alembic commands ###
