"""add_ai_generation_limits

Revision ID: b4843057bc06
Revises: 5aec72b895b6
Create Date: 2026-03-01 14:12:18.182138
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b4843057bc06'
down_revision: Union[str, None] = '5aec72b895b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studio_settings', sa.Column('ai_generations_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('studio_settings', sa.Column('ai_generations_reset_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studio_settings', 'ai_generations_reset_date')
    op.drop_column('studio_settings', 'ai_generations_count')
    # ### end Alembic commands ###
