"""add reschedule message templates

Revision ID: df4d148d9a3a
Revises: e767ea582721
Create Date: 2026-03-02 19:33:40.175769
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'df4d148d9a3a'
down_revision: Union[str, None] = 'e767ea582721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studio_settings', sa.Column('reschedule_wa_template', sa.Text(), nullable=True))
    op.add_column('studio_settings', sa.Column('reschedule_email_template', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studio_settings', 'reschedule_email_template')
    op.drop_column('studio_settings', 'reschedule_wa_template')
    # ### end Alembic commands ###
