"""add branding and configs

Revision ID: e5eef44da051
Revises: a295e9ff1025
Create Date: 2026-02-28 15:06:13.976836
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e5eef44da051'
down_revision: Union[str, None] = 'a295e9ff1025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studio_settings', sa.Column('smtp_host', sa.String(length=255), nullable=True))
    op.add_column('studio_settings', sa.Column('smtp_port', sa.Integer(), nullable=True))
    op.add_column('studio_settings', sa.Column('smtp_user', sa.String(length=255), nullable=True))
    op.add_column('studio_settings', sa.Column('smtp_pass', sa.String(length=255), nullable=True))
    op.add_column('studio_settings', sa.Column('smtp_from_email', sa.String(length=255), nullable=True))
    op.add_column('studio_settings', sa.Column('whatsapp_provider', sa.String(length=64), nullable=True))
    op.add_column('studio_settings', sa.Column('whatsapp_api_key', sa.String(length=255), nullable=True))
    op.add_column('studio_settings', sa.Column('whatsapp_phone_id', sa.String(length=255), nullable=True))
    op.add_column('studio_settings', sa.Column('theme_primary_color', sa.String(length=32), server_default='#000000', nullable=False))
    op.add_column('studio_settings', sa.Column('theme_secondary_color', sa.String(length=32), server_default='#ffffff', nullable=False))
    op.add_column('studio_settings', sa.Column('logo_filename', sa.String(length=255), nullable=True))
    op.add_column('studio_settings', sa.Column('landing_page_active_template', sa.Integer(), server_default='1', nullable=False))
    op.add_column('studio_settings', sa.Column('landing_page_title', sa.String(length=255), nullable=True))
    op.add_column('studio_settings', sa.Column('landing_page_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studio_settings', 'landing_page_description')
    op.drop_column('studio_settings', 'landing_page_title')
    op.drop_column('studio_settings', 'landing_page_active_template')
    op.drop_column('studio_settings', 'logo_filename')
    op.drop_column('studio_settings', 'theme_secondary_color')
    op.drop_column('studio_settings', 'theme_primary_color')
    op.drop_column('studio_settings', 'whatsapp_phone_id')
    op.drop_column('studio_settings', 'whatsapp_api_key')
    op.drop_column('studio_settings', 'whatsapp_provider')
    op.drop_column('studio_settings', 'smtp_from_email')
    op.drop_column('studio_settings', 'smtp_pass')
    op.drop_column('studio_settings', 'smtp_user')
    op.drop_column('studio_settings', 'smtp_port')
    op.drop_column('studio_settings', 'smtp_host')
    # ### end Alembic commands ###
