"""add post payment message templates

Revision ID: e767ea582721
Revises: 53c77417e218
Create Date: 2026-03-02 19:02:50.756821
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e767ea582721'
down_revision: Union[str, None] = '53c77417e218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studio_settings', sa.Column('post_payment_wa_template', sa.Text(), nullable=True))
    op.add_column('studio_settings', sa.Column('post_payment_email_template', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studio_settings', 'post_payment_email_template')
    op.drop_column('studio_settings', 'post_payment_wa_template')
    # ### end Alembic commands ###
