"""Add monthly_goals table

Revision ID: fbc23ca32511
Revises: 83f8238edcd4
Create Date: 2026-03-14 14:44:46.156948
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fbc23ca32511'
down_revision: Union[str, None] = '83f8238edcd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('studio_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studio_id', 'year', 'month', name='uq_monthly_goals_studio_date')
    )
    op.create_index(op.f('ix_monthly_goals_studio_id'), 'monthly_goals', ['studio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_goals_studio_id'), table_name='monthly_goals')
    op.drop_table('monthly_goals')
    # ### end Alembic commands ###
