"""add is_club_member

Revision ID: fff879aa5769
Revises: 82c42a87e991
Create Date: 2026-03-01 18:23:28.180038
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fff879aa5769'
down_revision: Union[str, None] = '82c42a87e991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('is_club_member', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'is_club_member')
    # ### end Alembic commands ###
